SELECT TOP(3) SHIPCOUNTRY, AVG(FREIGHT) AS AVGFREIGHT
FROM SALES.Orders
WHERE orderdate > '20140101' AND ORDERDATE < '20150101'
GROUP BY SHIPCOUNTRY, FREIGHT
ORDER BY AVGFREIGHT DESC;

SELECT CUSTID, ORDERDATE, ORDERID, ROW_NUMBER() OVER(PARTITION BY CUSTID
														ORDER BY ORDERDATE, ORDERID) AS ROWNUM
FROM SALES.Orders
ORDER BY CUSTID, ROWNUM;

SELECT EMPID, FIRSTNAME, LASTNAME, TITLEOFCOURTESY,
		CASE
			WHEN TITLEOFCOURTESY = 'MR.' THEN 'MALE'
			WHEN TITLEOFCOURTESY = 'MRS.' OR TITLEOFCOURTESY = 'MS.' THEN 'FEMALE'
			ELSE 'UNKNOWN'
		END AS GENDER
FROM HR.Employees;